### ISSUE TITLE
How do you create validations/callbacks?

### ISSUE THREAD

**Issue by onebree** [activeldap/activeldap#120]
**Rails 4.2.0, ActiveLDAP 4.0.4**

On our contacts page, I do not want the form to be submitted if there are blank fields. I am used to ActiveRecord validations and callbacks. How would I translate the following for the `Contact` LDAP model?

```ruby
class User < ActiveRecord::Base
  validates :givenName, presence: true
  validated :sn, presence: true
end
```

**Comment by kou** [comment]
Could you show your `Contact` model?

**Comment by onebree** [comment]
I do not think the Contact model is necessary to show. It contains no explicit validations (like an AR model), and is mostly company code.

The point is, I provided an ActiveRecord model. Is there a way to do similar validations with ActiveLDAP?

**Comment by kou** [comment]
Try like ActiveRecord:

```ruby
class User < ActiveLdap::Base
  validates :givenName, presence: true
  validated :sn, presence: true
end
```

I don't have any more advice without code.

**Comment by onebree** [comment]
Is there any built-in way to validate attributes with ActiveLDAP? I am assuming with the lack of help, that there is no way. Like I said, the model has nothing in it, besides logic for queries. There are no associations in it.

**Comment by kou** [comment]
I don't know what you want. Did you try the code in https://github.com/activeldap/activeldap/issues/120#issuecomment-122262703 ? Did the code work?
