### ISSUE TITLE
Slash in filter

### ISSUE THREAD

**Issue by AXVill** [activeldap/activeldap#123]
When I have tried to use slash in filter, I got NET::LDAP error:
My filter: 
> :filter=>"(&(objectCategory=user)(displayName=*)(extensionAttribute1=#{day}/#{month}*)"

Filter from log:
> :filter=>"(&(objectCategory=user)(displayName=*)(extensionAttribute1=10/09*)"

Error:
> Net::LDAP::FilterSyntaxInvalidError (Invalid filter syntax.)

But if try to use escape character for slash I get same error:
My filter:
> :filter=>"(&(objectCategory=user)(displayName=*)(extensionAttribute1=#{day}\/#{month}*)"

Filter from log:
>:filter=>"(&(objectCategory=user)(displayName=*)(extensionAttribute1=10\\\/09*)

With escape character for my escape character :( What can I do with it?

**Comment by kou** [comment]
How about `"10\\2f09"`?

**Comment by AXVill** [comment]
Yep! It works! Thank you! Sorry for disturb.

**Comment by kou** [comment]
You're welcome. :-)
