### ISSUE TITLE
How to internationalize ldap attributes

### ISSUE THREAD

**Issue by bsdmad** [activeldap/activeldap#124]
Hi, 

How can we internationalize ldap attributes, such as 'cn', 'mail', etc., with Ruby on Rails application?

ActiveLdap is similar to ActiveRecord, so I made config/locales/models/ja.yml as follows:

```ruby```
ja:
  activerecord:
    models:
      user:
    attributes:
      user:
        Name: 氏名・法人名
        Ipaddress: IP アドレス
        Cleartextpassword: パスワード
```

This doesn't work, and I tried to change "activerecord" with "activeldap", but (of course?) it also doesn't work.

Any comment will really help me :)

**Comment by kou** [comment]
ActiveLdap doesn't use i18n gem. It used gettext gem.

If you want to use i18n gem, try the following code:

```ruby
class User < ActiveLdap::Base
  extend ActiveModel::Naming
  extend ActiveModel::Translation

  class << self
    def i18n_scope
      :activeldap
    end
  end
end
```

It will refer `ja.activeldap.attributes.user.cn`.

**Comment by bsdmad** [comment]
Thanks, but the code doesn't work well. I'll check them deeply.

**Comment by bsdmad** [comment]
Reading activeldap & activemodel code, and I think a model based activeldap still uses ActiveLdap::HumanReadable::ClassMethods.human_attribute_name even with following code:

```ruby
class User < ActiveLdap::Base
  extend ActiveModel::Naming
  extend ActiveModel::Translation
(snip)
```

If so, can't we use I18n gem with activeldap?

**Comment by kou** [comment]
Try to add the following code:

```ruby
module ActiveLdap
  class Base
    class << self
      def i18n_scope
        :activeldap
      end
    end
  end

  module HumanReadable
    module ClassMethods
      remove_method :human_attribute_name
    end
  end
end
```

You don't need to change your ActiveLdap class (`User` class).

**Comment by bsdmad** [comment]
Fine! Thanks for your advice :)
