### ISSUE TITLE
Work with latest ruby version (Ruby 2.3)

### ISSUE THREAD

**Issue by weicheng** [activeldap/activeldap#126]
did ActiveLdap support latest ruby version ? if not is there any development plan for this?

**Comment by kou** [comment]
Use the latest ActiveLdap (4.0.5).

**Comment by weicheng** [comment]
Great! Thanks a lot!
Could you please also change the README Ruby intepreter ?

**Comment by kou** [comment]
> Could you please also change the README Ruby intepreter ?

Oops.
Could you send a pull request?

**Comment by weicheng** [comment]
Please check the pull request https://github.com/activeldap/activeldap/pull/127

**Comment by kou** [comment]
I've merged. Thanks!

**Comment by kou** [comment]
I've merged. Thanks!
