### ISSUE TITLE
why 'replace' instead of 'add'

### ISSUE THREAD

**Issue by arunkarthick** [activeldap/activeldap#142]
Hello,

When i try the following, ActiveLdap always choose the 'replace' operation, instead of 'add' operation.

```
class Group < ActiveLdap::Base
  has_many :members, class_name: 'User', wrap: 'memberUid', primary_key: 'uid'
end
```

```
g = Group.find('sample')
g.memberUid  # returns ['uid1', 'uid2']
g.memberUid = g.memberUid + ['uid3'] # returns ['uid1', 'uid2', 'uid3']
g.save # this save triggers the below ldap query 
```

`# LDAP: modify (180.4ms) {:dn=>"cn=sample,cn=groups,ou=example,ou=com", :attributes=>[[:replace, "memberUid", {"memberUid"=>["uid1", "uid2", "uid3"]}]]}`

My question is why 'replace' operation is triggered instead of 'add' operation here? All i am doing here is adding one more user to the group. But this will replace the entire attribute everytime if i add a single user to the group? i believe 'replace' means removing the attribute and adding the attribute again. Lets say if i have 1000's of members in a group, my ldap query will trigger 'replace' everytime if i add one more user to the same group which doesnt make any sense... May be i am missing something here?

Usually to add a user to a group, we do something like below using ldif

```
dn: cn=sample,cn=groups,ou=example,ou=com
changetype: modify
add: memberuid
memberuid: uid3
```

Is there any way to trigger 'add' instead of 'replace' for single user addition to a group?

Any thoughts?

**Comment by kou** [comment]
If you can implement using `add` when attribute value is added, I'll merge it.

`ActiveLdap::Base#collect_modified_attributes` will help you.

**Comment by depouill** [comment]
If you just want to take care of modifying one value in a mutlivalued attribute, this monkey patch works for me (I don't know about side-effects):

module ActiveLdap
  class Base
    def collect_modified_attributes(ldap_data, data)
      klass = self.class
      _dn_attribute = dn_attribute
      new_dn_value = nil
      attributes = []

      # Now that all the options will be treated as unique attributes
      # we can see what's changed and add anything that is brand-spankin'
      # new.
      ldap_data.each do |k, v|
        value = data[k] || []

        next if v == value

        value = klass.remove_blank_value(value) || []
        next if v == value

        if klass.blank_value?(value) and
          schema.attribute(k).binary_required?
          value = [{'binary' => []}]
        end
        if k == _dn_attribute
          new_dn_value = value[0]
        else
          # only one value changed (added or deleted)
          if (v.size-value.size).abs == 1
            if (value-v).size == 1
              # value has one more item than v: add one value
              attributes.push([:add, k, value-v])
            else
              attributes.push([:delete, k, v-value])
            end
          else
            attributes.push([:replace, k, value])
          end
        end
      end

      data.each do |k, v|
        value = v || []

        next if ldap_data.has_key?(k)

        value = klass.remove_blank_value(value) || []
        next if klass.blank_value?(value)

        # Detect subtypes and account for them
        # REPLACE will function like ADD, but doesn't hit EQUALITY problems
        # TODO: Added equality(attr) to Schema

        # add an attribute with one value
        if value.size == 1
          attributes.push([:add, k, value])
        else
          attributes.push([:replace, k, value])
        end
      end

      [new_dn_value, attributes]
    end
  end
end
