### ISSUE TITLE
alias_method_chain is deprecated

### ISSUE THREAD

**Issue by jas01** [activeldap/activeldap#146]
Maybe you already know that, but with the last version of active_ldap (activeldap (4.0.6)) with ruby (ruby-2.2.6) I got this message at the load 

DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from require at /usr/local/lib/ruby/site_ruby/2.2/rubygems/core_ext/kernel_require.rb:133)

Thanks for your work

**Comment by Laykou** [comment]
Was this already fixed? I'm using activeldap (4.0.6) and stil seeing this warning.

**Comment by kou** [comment]
I've fixed it and released 5.1.0.
