### ISSUE TITLE
Your website is broken

### ISSUE THREAD

**Issue by jedrekdomanski** [activeldap/activeldap#147]
I need to figure out a way to search for LDAP attributes and I was trying to see the usage of ActiveLDAP but can't read anything on your website. See the image below, it's broken.

![image](https://cloud.githubusercontent.com/assets/5911945/26823801/3b1d8f6c-4aaf-11e7-894a-9ee178e0804c.png)

**Comment by kou** [comment]
Thanks. I've fixed.

**Comment by jedrekdomanski** [comment]
Thanks :-)
