### ISSUE TITLE
How to access creatorsName ?

### ISSUE THREAD

**Issue by jas01** [activeldap/activeldap#150]
Hi everyone,

I'm trying to find the creatorsName attribute value (for any entry).  How can I do that ?

Regards.

**Comment by kou** [comment]
You can use `entry.creatorsName`.

**Comment by kou** [comment]
Can you show the output of `puts me.to_ldif`?

**Comment by jas01** [comment]
Le 12/01/2018 à 04:56:20-0800, Kouhei Sutou a écrit
Hi

> Can you show the output of puts me.to_ldif?
>
Yes off course :

(I manually « anonymize » the data so I don't think they are coherent
anymore).


irb(main):036:0> me=NewPersonsSimple.find('uid=mrecherche,ou=people,ou=XXXX') => #<NewPersonsSimple objectClass:<person, inetOrgPerson, organizationalPerson, supannPerson>, must:<cn, objectClass, sn>, may:<audio, businessCategory, carLicense, departmentNumber, description, destinationIndicator, displayName, employeeNumber, employeeType, facsimileTelephoneNumber, givenName, homePhone, homePostalAddress, initials, internationaliSDNNumber, jpegPhoto, l, labeledURI, mail, mailForwardingAddress, manager, mobile, o, ou, pager, photo, physicalDeliveryOfficeName, postOfficeBox, postalAddress, postalCode, preferredDeliveryMethod, preferredLanguage, registeredAddress, roomNumber, secretary, seeAlso, st, street, supannActivite, supannAffectation, supannAliasLogin, supannAutreMail, supannAutreTelephone, supannCivilite, supannCodeINE, supannEmpCorps, supannEmpId, supannEntiteAffectation, supannEntiteAffectationPrincipale, supannEtablissement, supannEtuAnneeInscription, supannEtuCursusAnnee, supannEtuDiplome, supannEtuElementPedagogique, supannEtuEtape, supannEtuId, supannEtuInscription, supannEtuRegimeInscription, supannEtuSecteurDisciplinaire, supannEtuTypeDiplome, supannListeRouge, supannMailPerso, supannOrganisme, supannParrainDN, supannRefId, supannRole, supannRoleEntite, supannRoleGenerique, supannTypeEntiteAffectation, telephoneNumber, teletexTerminalIdentifier, telexNumber, title, uid, userCertificate, userPKCS12, userPassword, userSMIMECertificate, x121Address, x500UniqueIdentifier>, audio: [], businessCategory: [], carLicense: [], cn: ["recherche master2"], commonName: ["recherche master2"], departmentNumber: ["BAT 02 - Grands Communs"], description: [], destinationIndicator: [], displayName: ["master2 recherche"], employeeNumber: [], employeeType: [], facsimileTelephoneNumber: [], fax: [], givenName: ["master2"], gn: ["master2"], homePhone: [], homePostalAddress: [], homeTelephoneNumber: [], initials: [], internationaliSDNNumber: [], jpegPhoto: [], l: [], labeledURI: [], localityName: [], mail: [], mailForwardingAddress: ["mrecherche@hermes.YYYYYY.fr"], manager: [], mobile: [], mobileTelephoneNumber: [], o: [], objectClass: ["person", "inetOrgPerson", "organizationalPerson", "supannPerson"], organizationName: [], organizationalUnitName: [], ou: [], pager: [], pagerTelephoneNumber: [], photo: [], physicalDeliveryOfficeName: [], postOfficeBox: [], postalAddress: [], postalCode: [], preferredDeliveryMethod: [], preferredLanguage: [], registeredAddress: [], rfc822Mailbox: [], roomNumber: [], secretary: [], seeAlso: [], sn: ["recherche"], st: [], stateOrProvinceName: [], street: [], streetAddress: [], supannActivite: [], supannAffectation: [], supannAliasLogin: [], supannAutreMail: [], supannAutreTelephone: [], supannCivilite: [], supannCodeINE: [], supannEmpCorps: [], supannEmpId: [], supannEntiteAffectation: [], supannEntiteAffectationPrincipale: [], supannEtablissement: [], supannEtuAnneeInscription: [], supannEtuCursusAnnee: [], supannEtuDiplome: [], supannEtuElementPedagogique: [], supannEtuEtape: [], supannEtuId: [], supannEtuInscription: [], supannEtuRegimeInscription: [], supannEtuSecteurDisciplinaire: [], supannEtuTypeDiplome: [], supannListeRouge: [false], supannMailPerso: [], supannOrganisme: [], supannParrainDN: [], supannRefId: [], supannRole: [], supannRoleEntite: [], supannRoleGenerique: [], supannTypeEntiteAffectation: [], surname: ["recherche"], telephoneNumber: ["0000"], teletexTerminalIdentifier: [], telexNumber: [], title: [], uid: ["mrecherche"], userCertificate: [], userPKCS12: [], userPassword: ["{SSHA}"], userSMIMECertificate: [], userid: ["mrecherche"], x121Address: [], x500UniqueIdentifier: []>

irb(main):038:0> me.to_ldif
=> "version: 1\ndn: uid=mrecherche,ou=people,ou=XXXX,dc=YYYYYY,dc=fr\ncn: recherche master2\ndepartmentNumber: XXXXXXX\ndisplayName: master2 recherche\ngivenName: master2\nmailForwardingAddress: mrecherche@YYYYYY.fr\nobjectClass: inetOrgPerson\nobjectClass: organizationalPerson\nobjectClass: person\nobjectClass: supannPerson\nsn: recherche\nsupannListeRouge: FALSE\ntelephoneNumber: 0000\nuid: mrecherche\nuserPassword: {SSHA}\n"
irb(main):039:0>

I think you know it, but creatorsName are part of those « specials »
attributes.

If you make a search with ldapsearch you not going to find it until you
specifically ask it


root@ldaps-p1:/home/root# /usr/bin/ldapsearch -o ldif-wrap=no -Y EXTERNAL -H ldapi:/// -b 'dc=XXXX,dc=fr' 'uid=mrecherche'
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
# extended LDIF
#
# LDAPv3
# base <dc=XXXX,dc=fr> with scope subtree
# filter: uid=mrecherche
# requesting: ALL
#

# mrecherche, people, YYYY, XXXX.fr
dn: uid=mrecherche,ou=people,ou=YYYY,dc=XXXX,dc=fr
uid: mrecherche
objectClass: person
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: supannPerson
cn: recherche master2
sn: recherche
givenName: master2
userPassword:: e1NTSEF9QVc2QWgzamw5bjdia3R6ZHhyUVpyQnZYNDFXVThUUEg=
displayName: master2 recherche
departmentNumber:
telephoneNumber: 00000
supannListeRouge: FALSE
mailForwardingAddress: mrecherche@XXXX.fr

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
root@ldaps-p1:/home/root# /usr/bin/ldapsearch -o ldif-wrap=no -Y EXTERNAL -H ldapi:/// -b 'dc=XXXX,dc=fr' 'uid=mrecherche' creatorsName
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
# extended LDIF
#
# LDAPv3
# base <dc=XXXX,dc=fr> with scope subtree
# filter: uid=mrecherche
# requesting: creatorsName
#

# mrecherche, people, YYYY, XXXX.fr
dn: uid=mrecherche,ou=people,ou=YYYY,dc=XXXX,dc=fr
creatorsName: cn=admin,dc=XXXX,dc=fr

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1

Regards

**Comment by kou** [comment]
Can you try `NewPersonsSimple.find('uid=mrecherche,ou=people,ou=XXXX', :attributes => ["*", "creatorsName"])`?

**Comment by jas01** [comment]
It's working perfectly. After the find I can access to the creatosName attribue by using entry.creatorsName.

Thanks you very much. 

For me the problem is solved, I let you decide if you want/like to add the 'creatorsName' as method automatically as those other attributes (https://www.novell.com/coolsolutions/tip/6027.html)

Regards

**Comment by kou** [comment]
Do you know why these attributes are required to specify explicitly?
If there are some reasonable reasons, we should not export them implicitly. It may be good that we add a convenient option such as `:include_operational_attributes`. If users use `XXX.find(..., :include_operational_attributes => true)` then these attributes are included.

**Comment by jas01** [comment]
I'm not very sure, I'm not a ldap specialist. 
As I understand those attributes are consider as "operationnal attributes", they are read-only as we can easly guess.  

When do you need it ? For example, if you manage you ldap no through a web gui you never need that (creatorsName) information, because the creatorsName would always be something "uid=webapi". But if you manage your ldap directly throught ldapadd (or script who was bind as user) this information would be the more accurate because it's write by the server not by the application. 
Same with those others attributes like `createTimeStamp`. It's more accurate to trust the server than the log of some web gui. 

But again I'm not a openldap guru. 

And that 
> It may be good that we add a convenient option such as :include_operational_attributes. If users use XXX.find(..., :include_operational_attributes => true) then these attributes are included

of course that would be awesome.....

**Comment by kou** [comment]
>> It may be good that we add a convenient option such as :include_operational_attributes. If users use XXX.find(..., :include_operational_attributes => true) then these attributes are included

> of course that would be awesome.....

Do you want to try to create a pull request for it?

**Comment by abhas** [comment]
In the past, I've used `:attributes => ["*", "+"]` to get all the operational attributes for whatever I'm querying.

For example,

```ruby
User.find(:all, :filter => '(mail=' + params[:id] + ')', :attributes => ["*", "+"]).first
```
returns the user's normal attributes plus the operational attributes as well.

This is very similar to what you would do on the command line using `ldapsearch` to query the operational attributes during a query.

Hope this helps...

**Comment by kou** [comment]
Do you know `+` is portable? If `+` is portable, we can use it in `:include_operational_attributes`.

**Comment by abhas** [comment]
I think it is portable. I have personally tested it against OpenLDAP and 389DS. I have also seen proprietary LDAP servers mention its use in their corresponding `ldapsearch` documentation.

**Comment by kou** [comment]
Thanks for the information.

**Comment by jas01** [comment]
> 
> 
>         It may be good that we add a convenient option such as :include_operational_attributes. If users use XXX.find(..., :include_operational_attributes => true) then these attributes are included
> 
>     of course that would be awesome.....
> 
> Do you want to try to create a pull request for it?

Well I don't think that's is for my skill level in ruby. I just clone and try to understand how it's work. But sadly I'm to dumb (currently ;-) ) to understand how to change that.

So if anyone want to do that. 

I will still try it but....don't wait me

**Comment by kou** [comment]
OK. I've implemented and released a new version.
I hope your try at the next change.
