### ISSUE TITLE
Misleading error log when not using YAML config

### ISSUE THREAD

**Issue by dklotz** [activeldap/activeldap#157]
In our (or rather our clients) rails application, we use ActiveLdap to talk to multiple different LDAP servers (one ActiveDirectory, one OpenLDAP etc.), so we can't use one global server configuration for the whole application. We created server-specific individual classes like `AD::User`, `OpenLDAP::User` etc. and we programmatically call `setup_connection` at the right time on them, which so far seems to work fine.

Now ActiveLdap still prints the following error log each time at startup:
```
[ERROR] You should run 'rails generator active_ldap:scaffold' to make /project/path/config/ldap.yml.
```

I've checked the ActiveLdap sources to make sure its really just printing an error and like I described it works fine, still our client is understandably not happy about a big red error log in their application logs. 

Is there any way to disable said error log when we're not using (and can't use since we need multiple server configs, and the application is completely configured through environment variables and not config files) the YAML config in any way?

**Comment by kou** [comment]
Ah, sorry. I missed this issue.
How about creating an empty `config/ldap.yml`? `setup_connection` does nothing until any operation is done.

**Comment by dklotz** [comment]
That does not seem to work. For a completely empty `ldap.yml` I get a `NoMethodError: undefined method '[]' for false:FalseClass` from [here](https://github.com/activeldap/activeldap/blob/5.2.1/lib/active_ldap/configuration.rb#L71) and if I just include an empty YAML map (i.e. `--- {}`) in the file, I get an `ActiveLdap::ConnectionError: test connection is not configured` from [here](https://github.com/activeldap/activeldap/blob/5.2.1/lib/active_ldap/configuration.rb#L73).

**Comment by dklotz** [comment]
Ok, now I've found a way which does not produce an error log or exception and still allows me to override the config, by including empty configurations for the specific environments in `ldap.yml` like this:
```
development: {}
test: {}
production: {}
```

Closing this since I now have a workaround and I see that our situation was pretty specific to begin with.

**Comment by kou** [comment]
OK!
