### ISSUE TITLE
ActiveLdap Associations - classes of different kind 

### ISSUE THREAD

**Issue by expeditioneer** [activeldap/activeldap#159]
Im using ActiveLdap with an Microsoft AD.

There I have a Record ('Domain Computers') with an entry - which could be either a single user or a group, is it possible and when yes how can these be modeled inside activeldap?

With Active Record I would use an abstract base class.

**Comment by kou** [comment]
Built-in `ActiveLdap::Entry` may help you: https://github.com/activeldap/activeldap/blob/master/lib/active_ldap/entry.rb

It accepts all LDAP entries including user and group.
