### ISSUE TITLE
Allow not verifying SSL certificates

### ISSUE THREAD

**Issue by HarlemSquirrel** [activeldap/activeldap#164]
It looks like we can [avoid verifying with start TLS](https://github.com/activeldap/activeldap/commit/edbf57ba4f0f99faa858bdae32f2fd2a858604d3), but that option does not seem to be respected with SSL. 

We can do this with Net LDAP with a configuration like this

```ruby
{
  host: 'example.com',
  port: 1636,
  auth: {
    method: :simple,
    username: 'admin-dn',
    password: 'admin-password'
  },
  encryption: {
    method: :simple_tls,
    tls_options: { 
      verify_mode: OpenSSL::SSL::VERIFY_NONE }
    }
  }
}
```

**Comment by kou** [comment]
Which LDAP backend library are you using? net-ldap? ruby-ldap?

**Comment by HarlemSquirrel** [comment]
We're currently using JRuby's built in LDAP support.

**Comment by kou** [comment]
For JRuby, JNDI backend is used by default: https://github.com/activeldap/activeldap/blob/master/lib/active_ldap/connection.rb#L197-L198

So we need to pass suitable options to JNDI in https://github.com/activeldap/activeldap/blob/master/lib/active_ldap/adapter/jndi_connection.rb

Do you want to try this?

**Comment by HarlemSquirrel** [comment]
Ok, I'm not familiar with how JNDI works but I can do some research this
week.

**Comment by kou** [comment]
Thanks!

**Comment by HarlemSquirrel** [comment]
I found https://stackoverflow.com/questions/4615163/how-to-accept-self-signed-certificates-for-jndi-ldap-connections but I'm not sure this is heading down the best path.

**Comment by kou** [comment]
Umm. I don't want to define custom Java class in this library.
Because we can't maintain it.

I think that you should use net-ldap backend. You can use `:tls_options` option for this purpose:

  * https://github.com/activeldap/activeldap/blob/master/lib/active_ldap/configuration.rb#L30
  * https://github.com/activeldap/activeldap/blob/master/lib/active_ldap/adapter/net_ldap.rb#L31

**Comment by HarlemSquirrel** [comment]
I got it working with `net-ldap`. Here's what I did. 

```sh
docker run -p 1389:389 -p 1636:636 --env LDAP_TLS_VERIFY_CLIENT=try --name openldap-test osixia/openldap --detach

ldapmodify -H ldap://localhost:1389 -D "cn=admin,dc=example,dc=org" -w admin -a <<+
dn: ou=people,dc=example,dc=org
changetype: add
objectClass: organizationalunit
objectClass: top
ou: people

dn: cn=Gandalf,ou=people,dc=example,dc=org
objectClass: person
objectClass: top
sn: the Grey
cn: Gandalf
+

gem install active_ldap net-ldap
```

```ruby
require 'active_ldap'

ActiveLdap::Base.setup_connection(
  host: 'localhost', 
  port: 1389, 
  base: 'dc=example,dc=org', 
  bind_dn: "cn=admin,dc=example,dc=org", 
  password: 'admin'
)

class Person < ActiveLdap::Base
  ldap_mapping
end
# => Person(objectClass:<top>, must:<objectClass: OID>, may:<>)

Person.first.attributes
# => {"objectClass"=>["person", "top"], "cn"=>"Gandalf", "sn"=>["the Grey"]}
```

```ruby
require 'active_ldap'

ActiveLdap::Base.setup_connection(
  host: 'localhost',
  port: 1636,
  method: :ssl,
  tls_options: { verify_mode: OpenSSL::SSL::VERIFY_NONE },
  base: 'dc=example,dc=org',
  bind_dn: "cn=admin,dc=example,dc=org",
  password: 'admin'
)

class Person < ActiveLdap::Base
  ldap_mapping
end
# not verifying SSL hostname of LDAPS server 'localhost:1636'
# => Person(objectClass:<top>, must:<objectClass: OID>, may:<>)

Person.first.attributes
# => {"objectClass"=>["person", "top"], "cn"=>"Gandalf", "sn"=>["the Grey"]}
```

**Comment by kou** [comment]
Thanks for sharing this.
I close this.
