### ISSUE TITLE
Remove attribute

### ISSUE THREAD

**Issue by jas01** [activeldap/activeldap#175]
Hi everyone.

I'm trying to remove a «non-standard» attribute. I mean a attribute pwdAccountLockedTime from ppolicy overlay. 

So because I think that's are a non standard attribute, activeldap cannot find it when the connection are made, so for modifying the attribute I'm using 
          
```ruby
 user.assign_attributes(['pwdAccountLockedTime'])
 user.pwdAccountLockedTime = '000001010000Z'
```

and it's working. But now I'm unable to delete/remove this attribute. 

Don't think it's a issue with activeldap, but with me ...

**Comment by kou** [comment]
Does the following resolve this?

```ruby
user = User.find(cn, attributes: ["*", "pwdAccountLockedTime"]
user.pwdAccountLockedTime = nil
user.save!
```

**Comment by jas01** [comment]
> 
> ```ruby
> user = User.find(cn, attributes: ["*", "pwdAccountLockedTime"]
> user.pwdAccountLockedTime = nil
> user.save!
> ```

ABSOLUTELY !!!. 

Work like ... activeldap... perfectly.

Thanks a lot.
