### ISSUE TITLE
Support for Rails 7 // Is this project still maintained?

### ISSUE THREAD

**Issue by t3k4y** [activeldap/activeldap#190]
Hello and thank you for this useful gem!

I cannot find any hint if this project is alive and maybe working on support for Rails > 5.

Thank you for your answer!

**Comment by kou** [comment]
It seems that this works with Rails 7: https://github.com/activeldap/activeldap/actions/runs/5274536146

I can answer for issues and review pull requests of this. But if you don't want to contribute to this when you find a problem or something, I don't recommend that you use this.
