### ISSUE TITLE
logging?

### ISSUE THREAD

**Issue by solars** [activeldap/activeldap#68]
Hi there,

Is it somehow possible to log queries?
Wireshark is not an option as I can only connect via ssl to our server...

I've got a belongs_to association that doesn't return anything, so I wanted to debug...

Thanks a lot,
Christoph

**Comment by onebree** [comment]
Hello. I am interested in this as well. I need to log the LDAP connection name and id being used when performing a query. I am trying to list all instances in which our ldap server is running to debug and possibly find zombie connections.

I am using Ruby 2.1.2, and latest version of activeldap

**Comment by onebree** [comment]
Ping @kou or even @solars for help.

**Comment by kou** [comment]
What is LDAP connection name? ActiveLdap doesn't name each connection...

Could you open new issue for this topic? It seems that this topic is another topic.
